#项目相关配置
EMSys:
  # 名称
  name: EMS
  # 版本
  version: 1.0
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径
  profile: F:/EM/uploadPath
  # 获取ip地址开关
  addressEnabled: true

#开发环境配置
server:
  port: 9704
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30

#日志配置
logging:
  level:
    org.wiki: debug
    org.springframework: warn
